//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBookmaster3000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int Id { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Bio { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public string Wikipedia { get; set; }
    }
}
