//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBookmaster3000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookauthor
    {
        public int id { get; set; }
        public int bookid { get; set; }
        public int authorid { get; set; }
    }
}
